Counting objects: 100% (90/90), done.
Delta compression using up to 8 threads
Compressing objects: 100% (81/81), done.
Writing objects: 100% (90/90), 84.48 KiB | 2.82 MiB/s, done.
Total 90 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), done.
To https://github.com/eduall2005pass/FW.git
 * [new branch]      main -> main
~/FW $
